### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Review by lucaferranti — APPROVED** [review]

**Comment by mforets** [comment]
Should we add a table with the available algorithms in the README?

**Review by schillic — APPROVED** [review]

**Comment by schillic** [comment]
> Should we add a table with the available algorithms in the README?

Up to you. I would consider that too technical for the average user, but it may be interesting for some. Generally I am fine if the README only shows the general use case and other things are found in the docs.

**Comment by mforets** [comment]
Ok. About the example that we present, wouldn't it be nice to show how the result obtained compares to the actual (analytical) solution?

**Comment by mforets** [comment]
Besides, we can emphasize that some methods are sound and rigorous, while others only just sound. Another use case for the table, but I agree that we can have it in the docs.

**Comment by schillic** [comment]
Yes, and we can also show that there are several algorithms available.

**Comment by lucaferranti** [comment]
> Besides, we can emphasize that some methods are sound and rigorous, while others only just sound. Another use case for the table, but I agree that we can have it in the docs.

yes such a detailed table should go in the docs. In the readme it could be ok to have a short list of available algorithms (since they're not too many) after the quickstart example. Or just something like "for a complete list of available algorithms see <link to list of algorithms in docs>"

**Pull request merged**
