### PR TITLE
Auto-format script

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by lucaferranti** [comment]
SDPA windows compatibility strikes again 😱

**Comment by lucaferranti** [comment]
```
2023-06-24T06:14:51.8846900Z [90m   @[39m [90m[4mnone:6[24m[39m
2023-06-24T06:14:51.9553753Z [33m[1m     Testing[22m[39m Precompilation of test environment failed. Continuing to tests
```

**Comment by lucaferranti** [comment]
https://github.com/jump-dev/SDPA.jl/pull/57 seems sdpa is broken on windows

**Comment by schillic** [comment]
Thanks, so this is an external issue and independent of the changes here. Then I merge.

**Pull request merged**
